### ISSUE TITLE
Queue submission interactive additions

### ISSUE THREAD

**Issue by mgt16-LANL** [pyiron/pyiron_base#1045]
Hi All,

In interacting with clusters with mutliple users on different accounts and potentially unreliable nodes, adding options for 1. runtime assignment of nodes to exclude and 2. slurm accounts (for example) to utilize for the jobs - having integrations with something like setting job.server.exclude and job.server.account would be ideal. As far as I can tell this change would involve pysqa and the pyiron_base libraries.

-Michael.

**Comment by pmrv** [comment]
Hi Michael,

when you want to exclude nodes, would that list change dynamically or only from time to time?

In case of not so frequent updates the solution would be to add new queue configurations that exclude the (suspected) faulty nodes.  In the pyiron resources folder you should have a file `queues/queues.yaml` which specifies what pyiron tries to submit to. It might look like this

```yaml
queue_type: SLURM
queue_primary: not_faulty
queues:
  all: {cores_max: 1200, cores_min: 1, run_time_max: 345600, script: all.sh}
  not_faulty: {cores_max: 1200, cores_min: 1, run_time_max: 345600, script: not_faulty.sh}
```

In that same directory you can place the submission scripts and change `not_faulty.sh` to exclude the nodes you don't want via normal SLURM features, e.g. adding the `--contraints` or `--partition` flags.

I'm not sure how SLURM handles submitting as different users.  You could try to use the `--uid` flag of sbatch in a similar as I sketched above and make a queue definition for each user.

@jan-janssen Do you know how we handle multiple queue definitions right now from the config side? If a user provide their own `queues/queues.yaml` in their own resources is that merged or does it replace any global queue definition that might exist?
